name = "ConformalCovariantOperators"
version = "0.1.0"
defaultTargets = ["conformalcovariantoperators"]

[[lean_lib]]
name = "ConformalCovariantOperators"

[[lean_exe]]
name = "conformalcovariantoperators"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0"
